version: '3'
services:
  odsupercomponent:
    image: kemekaze/vdodv:v0.1
    network_mode: "host"
    command: "odsupercomponent --cid=${CID} --configuration=/config/configuration"
  vDODV:
    image: kemekaze/vdodv:v0.1
    network_mode: "host"
    environment:
      - SDL_VIDEO_X11_VISUALID=0x022
      - DISPLAY=unix$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: "/app/build/vDODV --cid ${CID} -disableGUI"
  vDODV-test-path:
    depends_on:
      - vDODV
    image: kemekaze/vdodv:v0.1
    network_mode: "host"
    volumes:
        - ./runs/:/runs
        - ./test_cases/:/test_cases
    command: "/tests/build/path/vDODV-test-path --cid=${CID} "
  vDODV-model:
    depends_on:
      - vDODV
      - odsupercomponent
    image: kemekaze/vdodv:v0.1
    network_mode: "host"
    command: "/opt/opendlv.lynx/bin/opendlv-sim-lynx-bicyclemodel --cid=${CID} --freq=20"
