version: '3'
services:
  odsupercomponent:
    build: .
    image: kemekaze/vdodv
    network_mode: "host"
    command: "odsupercomponent --cid=${CID} --configuration=/app/config/configuration"
  vDODV:
    build: .
    image: kemekaze/vdodv
    network_mode: "host"
    environment:
      - SDL_VIDEO_X11_VISUALID=0x022
      - DISPLAY=${WIN_DISPLAY}
    command: "/app/build/vDODV --cid ${CID}"
  vDODV-test-input:
    depends_on:
      - vDODV
    build: .
    image: kemekaze/vdodv
    network_mode: "host"
    environment:
      - SDL_VIDEO_X11_VISUALID=0x022
      - DISPLAY=${WIN_DISPLAY}
    command: "/tests/build/vDODV-test-input --cid=${CID}"
  vDODV-model:
    depends_on:
      - vDODV
      - odsupercomponent
    build: .
    image: kemekaze/vdodv
    network_mode: "host"
    command: "/opt/opendlv.lynx/bin/opendlv-sim-lynx-bicyclemodel --cid=${CID}"
