version: '3'
services:
  odsupercomponent:
    build: .
    image: kemekaze/vdodv:v0.1
    network_mode: "host"
    command: "odsupercomponent --cid=${CID} --configuration=/config/configuration"
  vDODV:
    build: .
    image: kemekaze/vdodv:v0.1
    network_mode: "host"
    environment:
      - SDL_VIDEO_X11_VISUALID=0x022
      - DISPLAY=${WIN_DISPLAY}
    command: "/app/build/vDODV --cid ${CID}"
  vDODV-test-path:
    depends_on:
      - vDODV
    build: .
    image: kemekaze/vdodv:v0.1
    network_mode: "host"
    volumes:
        - ./runs/:/runs
        - ./test_cases/:/test_cases
    command: "/tests/build/path/vDODV-test-path --cid=${CID}"
  vDODV-model:
    depends_on:
      - vDODV
      - odsupercomponent
    build: .
    image: kemekaze/vdodv:v0.1
    network_mode: "host"
    command: "/opt/opendlv.lynx/bin/opendlv-sim-lynx-bicyclemodel --cid=${CID} --freq=20 "
