version: '3'
services:
  vDODV:
    build: .
    image: kemekaze/vdodv
    network_mode: "host"
    environment:
      - SDL_VIDEO_X11_VISUALID=0x022
      - DISPLAY=unix$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
