version: '3'
services:
  odsupercomponent:
    build: .
    image: kemekaze/vdodv
    network_mode: "host"
    command: "odsupercomponent --cid=${CID} --configuration=/app/config/configuration"
  vDODV:
    build: .
    image: kemekaze/vdodv
    network_mode: "host"
    environment:
      - SDL_VIDEO_X11_VISUALID=0x022
      - DISPLAY=unix$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: "/app/build/vDODV --cid ${CID}"
  vDODV-test-input:
    depends_on:
      - vDODV
    build: .
    image: kemekaze/vdodv
    network_mode: "host"
    environment:
      - SDL_VIDEO_X11_VISUALID=0x022
      - DISPLAY=unix$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: "/tests/build/input/vDODV-test-input --cid=${CID}"
  vDODV-test-path:
    depends_on:
      - vDODV
    build: .
    image: kemekaze/vdodv
    network_mode: "host"
    command: "/tests/build/path/vDODV-test-path --cid=${CID}"
  vDODV-model:
    depends_on:
      - vDODV
      - odsupercomponent
    build: .
    image: kemekaze/vdodv
    network_mode: "host"
    command: "/opt/opendlv.lynx/bin/opendlv-sim-lynx-bicyclemodel --cid=${CID}"
