version: '3'
services:
  vDODV:
    build: .
    image: kemekaze/vdodv
    network_mode: "host"
    environment:
      - SDL_VIDEO_X11_VISUALID=0x022
      - DISPLAY=192.168.1.2:0.0
    command: "/app/build/vDODV"
  vDODV-test-input:
    depends_on:
      - vDODV
    build: .
    image: kemekaze/vdodv
    network_mode: "host"
    environment:
      - SDL_VIDEO_X11_VISUALID=0x022
      - DISPLAY=192.168.1.2:0.0
    command: "/tests/build/vDODV-test-input"
